const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process'),Database=require('better-sqlite3');
test('backup y restore verifican hashes y preservan datos y archivos en otra ruta',()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'academiave-backup-test-')),source=path.join(tmp,'source'),target=path.join(tmp,'target');fs.mkdirSync(path.join(source,'uploads/private'),{recursive:true});fs.writeFileSync(path.join(source,'uploads/private/fixture.pdf'),'private-fixture');
 const baseEnv={...process.env,DATA_DIR:source,PUBLIC_UPLOAD_DIR:path.join(source,'public'),DB_FILE:path.join(source,'academy.sqlite'),LOG_LEVEL:'error'};
 try{
  const init=spawnSync(process.execPath,['src/db/migrate-cli.js'],{cwd:path.join(__dirname,'..'),env:baseEnv,encoding:'utf8'});assert.equal(init.status,0);const original=new Database(baseEnv.DB_FILE);original.prepare("INSERT INTO users(name,email,password_hash,role) VALUES('Test','backup@test.local','preserved-hash','student')").run();original.close();
  const backup=spawnSync(process.execPath,['scripts/backup.js','--confirm-stopped'],{cwd:path.join(__dirname,'..'),env:baseEnv,encoding:'utf8'});assert.equal(backup.status,0,backup.stderr);const folder=backup.stdout.trim().split('\n').at(-1);assert.ok(fs.existsSync(path.join(folder,'manifest.json')));
  const db=new Database(path.join(folder,'academy.sqlite'),{readonly:true});const count=db.prepare('SELECT COUNT(*) n FROM schema_migrations').get().n;assert.equal(count,4);db.close();
  fs.mkdirSync(path.join(target,'uploads/private'),{recursive:true});fs.writeFileSync(path.join(target,'uploads/private/extra.mp4'),'extra');
  const env={...baseEnv,DATA_DIR:target,PUBLIC_UPLOAD_DIR:path.join(target,'public'),DB_FILE:path.join(target,'academy.sqlite')};const restore=spawnSync(process.execPath,['scripts/restore.js',folder,'--confirm-stopped'],{cwd:path.join(__dirname,'..'),env,encoding:'utf8'});assert.equal(restore.status,0,restore.stderr);assert.equal(fs.existsSync(path.join(target,'uploads/private/extra.mp4')),false);assert.equal(fs.readFileSync(path.join(target,'uploads/private/fixture.pdf'),'utf8'),'private-fixture');const restored=new Database(env.DB_FILE);assert.equal(restored.prepare("SELECT password_hash FROM users WHERE email='backup@test.local'").get().password_hash,'preserved-hash');restored.close();
  fs.appendFileSync(path.join(folder,'private/fixture.pdf'),'corruption');const broken=spawnSync(process.execPath,['scripts/restore.js',folder,'--confirm-stopped'],{cwd:path.join(__dirname,'..'),env,encoding:'utf8'});assert.equal(broken.status,1);assert.match(broken.stderr,/alterado o incompleto/);assert.ok(fs.existsSync(path.join(target,'academy.sqlite')));
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
