const test=require('node:test'),assert=require('node:assert/strict');
const {safeNavigationUrl,safeGoogleMapsEmbed}=require('../src/utils/text');const {isPublicAddress}=require('../src/services/remote-template');const {validateSettings}=require('../src/services/cms-schema');const {validateBuffer}=require('../src/services/files');const {fittedLines}=require('../src/services/certificates');const {sanitizeLayout}=require('../src/services/certificate-layout');
test('SSRF rechaza redes reservadas, IPv6 local y direcciones mapeadas',()=>{for(const ip of ['127.0.0.1','10.2.3.4','172.20.0.1','192.168.1.2','169.254.169.254','100.64.0.1','0.0.0.0','198.18.0.2','::1','fe80::1','fc00::1','::ffff:127.0.0.1','2001:db8::1','2002:7f00:1::'])assert.equal(isPublicAddress(ip),false,ip);for(const ip of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111'])assert.equal(isPublicAddress(ip),true,ip);});
test('enlaces seguros rechazan redirects con backslash y credenciales',()=>{for(const url of ['//evil.test','/\\evil.test','https://user:password@example.com','javascript:alert(1)','/\n/evil'])assert.equal(safeNavigationUrl(url),'');assert.equal(safeNavigationUrl('/aula/ia?lesson=1'),'/aula/ia?lesson=1');assert.equal(safeGoogleMapsEmbed('https://evil.google.com/maps/embed'),'');assert.equal(safeGoogleMapsEmbed('https://www.google.com/search?q=x'),'');});
test('CMS aplica esquema por tipo y bloquea HTML, URLs y claves arbitrarias',()=>{for(const settings of [{title:'<img onerror=alert(1)>'},{title:'<script>x</script>'},{href:'javascript:alert(1)'},{href:'/\\evil.test'},{onclick:'boom'},{__proto__:{evil:1},imageUrl:'data:text/html,x'},{columns:10}])assert.throws(()=>validateSettings('cta',settings));assert.deepEqual(validateSettings('cta',{title:'Inscríbete',href:'/catalogo',columns:'2',mobileHidden:'0'}),{title:'Inscríbete',href:'/catalogo',columns:2,mobileHidden:false});});
test('upload rechaza firma incompleta, MIME falseado y tamaño real excedido',()=>{assert.throws(()=>validateBuffer({buffer:Buffer.from('%PDF-1.7\n'),size:9},{allow:['pdf']}));const pdf=Buffer.from('%PDF-1.7\n%%EOF');assert.throws(()=>validateBuffer({buffer:pdf,size:1,mimetype:'image/png'},{allow:['pdf']}));assert.throws(()=>validateBuffer({buffer:pdf,size:1},{allow:['pdf'],maxBytes:3}));assert.equal(validateBuffer({buffer:pdf,mimetype:'application/pdf'},{allow:['pdf']}).mime,'application/pdf');});
test('ajuste de certificado divide palabras largas y falla sin omitir contenido',()=>{const font={widthOfTextAtSize:(text,size)=>[...text].length*size*.6};const fitted=fittedLines(font,'PALABRAMUYLARGA'.repeat(4),12,{width:100,height:300});assert.ok(fitted.lines.every(line=>font.widthOfTextAtSize(line,fitted.size)<=100));assert.equal(fitted.lines.join(''),'PALABRAMUYLARGA'.repeat(4));assert.throws(()=>fittedLines(font,'muchas líneas '.repeat(100),12,{width:20,height:10}),e=>e.status===422);});
test('visibilidad false y estilo negrita+cursiva sobreviven al saneado',()=>{const layout=sanitizeLayout({front:{student_name:{enabled:'false',style:'boldItalic'}}});assert.equal(layout.front.student_name.enabled,false);assert.equal(layout.front.student_name.style,'boldItalic');});

test('campos ampliados permanecen dentro de A4 aun sin coordenadas explícitas',()=>{const layout=sanitizeLayout({front:{student_name:{width:100,height:90}}});assert.equal(layout.front.student_name.x,0);assert.equal(layout.front.student_name.y,10);});
