/* Optional QA tool: npm install --no-save --package-lock=false playwright && npx playwright install chromium */
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'academiave-browser-'));
process.env.NODE_ENV='test';process.env.DATA_DIR=temporary;process.env.PUBLIC_UPLOAD_DIR=path.join(temporary,'public');process.env.DB_FILE=path.join(temporary,'academy.sqlite');process.env.SESSION_SECRET='qa-session-secret-0123456789-abcdefghijklmnopqrstuvwxyz';process.env.ADMIN_EMAIL='admin@qa.local';process.env.ADMIN_PASSWORD='QA-admin-password-2026!';process.env.EXCHANGE_RATE='150';process.env.LOG_LEVEL='warn';
const {createApp}=require('../src/app');const {closeDatabase}=require('../src/db');
const out=path.resolve(process.env.QA_OUTPUT||'qa/browser');fs.mkdirSync(out,{recursive:true});
async function run(){
 const playwright=require(process.env.PLAYWRIGHT_MODULE||'playwright');
 const browser=await playwright.chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});
 const app=createApp();let server;await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});const base=`http://127.0.0.1:${server.address().port}`;
 const results={browser:browser.version(),widths:[360,390,414,768,1024,1280,1440],pages:[],flows:[],errors:[],overflows:[]};
 const admin=await browser.newContext(),student=await browser.newContext(),guest=await browser.newContext();
 async function request(context,url,method='GET',body,token){const response=await context.request.fetch(base+url,{method,data:body,headers:token?{'x-csrf-token':token}:{}});const data=await response.json();assert.ok(response.ok(),`${method} ${url} ${response.status()} ${JSON.stringify(data)}`);return data;}
 try{
  const admMe=await request(admin,'/api/auth/me');const adm=await request(admin,'/api/auth/login','POST',{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD},admMe.csrfToken);
  const me=await request(student,'/api/auth/me');const stu=await request(student,'/api/auth/register','POST',{name:'María Fernanda Rojas · Alumna de formación profesional',email:'student@qa.local',password:'QA-student-password-2026!'},me.csrfToken);
  await request(admin,'/api/admin/settings','PUT',{academy_name:'Academia de Formación Profesional y Tecnología de Venezuela',exchange_rate:'150'},adm.csrfToken);
  await request(admin,'/api/admin/locations','POST',{name:'Sede Caracas',address:'Av. de ejemplo · Caracas',description:'Atención con cita previa',active:1},adm.csrfToken);
  await request(admin,'/api/admin/coupons','POST',{code:'QA20',discount_type:'percent',discount_value:20,max_uses:10},adm.csrfToken);
  const created=await request(admin,'/api/admin/courses','POST',{name:'Formación profesional en inteligencia artificial aplicada y estrategia digital',slug:'qa-course',price_usd:25,duration_hours:40,status:'published',featured:1,category:'Tecnología',level:'Principiante',description:'Un curso práctico para aplicar tus conocimientos.',long_description:'Aprende herramientas, metodología y buenas prácticas.'},adm.csrfToken);
  for(let n=1;n<=6;n++)await request(admin,`/api/admin/courses/${created.course.id}/lessons`,'POST',{title:`${n}. Fundamentos y aplicaciones de inteligencia artificial en entornos profesionales`,description:'Objetivos y actividades de la clase.',content:'Contenido de ejemplo.\nAplica el ejercicio y marca la clase como completada.',status:'published',sort_order:n,is_free:n===1},adm.csrfToken);
  const sp=await student.newPage();await sp.goto(base+'/pago?course=qa-course');await sp.locator('#payment-form').waitFor();
  for(const [id,value]of Object.entries({payerName:'María Rojas',payerBank:'Banco Test',payerPhone:'04141234567',payerDocument:'V-12345678',reference:'QA-BROWSER-0001',couponCode:'QA20'}))await sp.locator('#'+id).fill(value);
  await sp.locator('#receipt').setInputFiles(path.resolve('public/uploads/certificates/demo-front.png'));await sp.locator('#payment-submit:not([disabled])').waitFor();
  await sp.getByRole('button',{name:'Enviar pago para revisión'}).click();await sp.waitForURL('**/dashboard');results.flows.push('Pago enviado mediante formulario real con cupón y comprobante PNG');
  const payments=await request(admin,'/api/admin/payments');const pending=payments.payments.find(p=>p.reference==='QA-BROWSER-0001');assert.equal(pending.amount,20);assert.equal(pending.amount_bs,3000);
  const ap=await admin.newPage();ap.on('dialog',dialog=>dialog.accept());await ap.goto(base+'/admin/pagos');await ap.locator(`[data-approve="${pending.id}"]`).click();await ap.locator('[data-approve]').waitFor({state:'detached'});results.flows.push('Aprobación administrativa en UI y matrícula automática');
  await sp.goto(base+'/aula/qa-course');await sp.locator('#toggle-progress').waitFor();
  await sp.locator('#toggle-progress').click();await sp.getByRole('button',{name:'Marcar como pendiente',exact:true}).waitFor();await sp.locator('#toggle-progress').click();await sp.getByRole('button',{name:'Marcar como completada',exact:true}).waitFor();
  await sp.locator('#next-lesson').click();await sp.locator('#previous-lesson').click();
  const classroom=await request(student,'/api/courses/qa-course/classroom');for(const lesson of classroom.lessons)await request(student,`/api/lessons/${lesson.id}/progress`,'POST',{completed:true},stu.csrfToken);
  const cert=await request(student,'/api/courses/qa-course/certificate','POST',{},stu.csrfToken);results.flows.push('Anterior/siguiente y completada/pendiente en UI; emisión del certificado tras completar seis clases');
  await ap.goto(base+'/admin/cursos');await ap.locator('#new-course').click();await ap.getByRole('dialog').waitFor();assert.equal(await ap.getByRole('dialog').getAttribute('aria-labelledby'),'modal-title');await ap.keyboard.press('Escape');assert.equal(await ap.getByRole('dialog').count(),0);
  await ap.locator(`[data-lessons="${created.course.id}"]`).click();await ap.locator('#add-lesson').click();await ap.locator('#lesson-form').waitFor();await ap.keyboard.press('Escape');results.flows.push('Nueva clase abre sin error; modales etiquetados y Escape cierra');
  await ap.goto(base+'/admin/certificados');await ap.locator('[data-cert-field="student_name"]').waitFor();
  const field=ap.locator('[data-cert-field="student_name"]');const x=Number(await ap.locator('#certificate-field-x').inputValue());await field.focus();await ap.keyboard.press('ArrowRight');assert.ok(Number(await ap.locator('#certificate-field-x').inputValue())>x);
  const box=await field.boundingBox();await ap.mouse.move(box.x+box.width/2,box.y+box.height/2);await ap.mouse.down();await ap.mouse.move(box.x+box.width/2+25,box.y+box.height/2+12,{steps:5});await ap.mouse.up();await ap.locator('#save-certificate-layout').click();
  await ap.locator('[data-cert-side="back"]').click();await ap.locator('#certificate-field-style').selectOption('boldItalic');await ap.locator('#save-certificate-layout').click();
  const savedLayout=await request(admin,'/api/admin/certificates/layout');assert.equal(savedLayout.layout.back.content.style,'boldItalic');await ap.locator('#reset-certificate-layout').click();const resetLayout=await request(admin,'/api/admin/certificates/layout');assert.equal(resetLayout.layout.front.student_name.x,16);
  const response=await admin.request.get(base+'/api/admin/certificates/preview.pdf');assert.equal(response.status(),200);fs.writeFileSync(path.join(out,'preview.pdf'),await response.body());results.flows.push('Certificados: flechas, arrastre, guardado, reverso, negrita+cursiva y PDF ficticio');
  const real=await student.request.get(base+`/api/certificates/${cert.certificate.code}/pdf`);assert.equal(real.status(),200);fs.writeFileSync(path.join(out,'certificate.pdf'),await real.body());
  await ap.goto(base+'/admin/cms');await ap.locator('#cms-inspector-form').waitFor();const blocks=await ap.locator('.cms-block').count();await ap.locator('[data-move="0"][data-direction="1"]').click();await ap.locator('#cms-save').click();await ap.getByText('Borrador guardado.',{exact:true}).waitFor();assert.equal(await ap.locator('.cms-block').count(),blocks);results.flows.push('CMS: reordenamiento por botón y guardado del borrador');
  // Explicitly reproduce a failed save and ensure no publish request follows it.
  let publishAttempts=0;ap.on('request',r=>{if(r.url().endsWith('/publish'))publishAttempts++;});await ap.route('**/api/admin/cms/home/draft',route=>route.request().method()==='PUT'?route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Error de prueba al guardar'})}):route.continue());await ap.locator('#cms-publish').click();await ap.getByText('Error de prueba al guardar',{exact:true}).waitFor();assert.equal(publishAttempts,0);await ap.unroute('**/api/admin/cms/home/draft');results.flows.push('CMS: publicación bloqueada tras rechazo del guardado (HTTP 400 simulado)');
  const gp=await guest.newPage();
  // New product flows: actual controls, persistence and safe live rendering.
  await gp.goto(base+'/login');await gp.locator('#password').waitFor();await gp.locator('[data-toggle-password="password"]').click();assert.equal(await gp.locator('#password').getAttribute('type'),'text');assert.equal(await gp.locator('[data-toggle-password="password"]').getAttribute('aria-pressed'),'true');await gp.locator('[data-toggle-password="password"]').click();assert.equal(await gp.locator('#password').getAttribute('type'),'password');results.flows.push('Mostrar/Ocultar integrado, accesible y reversible');
  await gp.goto(base+'/catalogo');await gp.locator('#minPrice').fill('20');await gp.locator('#maxPrice').fill('29');await gp.getByRole('button',{name:'Aplicar filtros'}).click();await gp.waitForFunction(()=>document.querySelector('#catalog-count')?.textContent==='1 cursos encontrados');assert.equal(await gp.locator('#catalog-results .course-card').count(),1);assert.ok(gp.url().includes('minPrice=20'));await gp.locator('#clear-filters').click();await gp.waitForFunction(()=>document.querySelector('#catalog-count')?.textContent==='3 cursos encontrados');results.flows.push('Filtros de precio, contador, URL y limpieza de catálogo');
  await gp.setViewportSize({width:390,height:900});await gp.goto(base+'/');const track=gp.locator('.carousel__track');await track.waitFor();await track.focus();await gp.keyboard.press('ArrowRight');await gp.waitForFunction(()=>document.querySelector('.carousel__track').scrollLeft>0);await gp.locator('.carousel__dot').last().click();await gp.waitForFunction(()=>document.querySelector('.carousel__dot:last-child').getAttribute('aria-current')==='true');results.flows.push('Carrusel móvil operado con teclado y dots');
  await ap.goto(base+'/admin/diseno');await ap.locator('#design-form').waitFor();const originalDesign=(await request(admin,'/api/admin/settings')).design;await ap.locator('[name="primary"]').fill('#123456');await ap.locator('[name="button_style"]').selectOption('pill');assert.equal(await ap.locator('.design-preview').evaluate(el=>el.style.getPropertyValue('--primary')),'#123456');assert.notEqual(await ap.evaluate(()=>document.documentElement.style.getPropertyValue('--primary')),'#123456');await ap.getByRole('button',{name:'Guardar diseño',exact:true}).click();await ap.getByText('Design System actualizado.',{exact:true}).waitFor();assert.equal((await request(admin,'/api/admin/settings')).design.button_style,'pill');await request(admin,'/api/admin/design','PUT',originalDesign,adm.csrfToken);results.flows.push('Tema: vista local sin publicar, guardado de botones y persistencia');
  await ap.goto(base+'/admin/configuracion');await ap.locator('#nav-add').click();assert.equal(await ap.locator('.navigation-row').count(),(await request(admin,'/api/admin/navigation')).items.length+1);await ap.locator('[data-nav-remove]').last().click();await ap.locator('#nav-form button[type="submit"]').click();await ap.getByText('Navegación guardada. Se verá al recargar la página.',{exact:true}).waitFor();results.flows.push('Editor de navegación: añadir, quitar y guardar enlaces');
  await ap.goto(base+'/admin/cms');await ap.locator('[data-select="1"]').click();await ap.locator('[name="settings.title"]').fill('Aprende hoy. Transforma tu mañana.');await ap.locator('[name="settings.backgroundColor"]').fill('#eef4f0');await ap.locator('[name="settings.textColor"]').fill('#142d2a');await ap.locator('[name="settings.accentColor"]').fill('#006b5f');assert.equal(await ap.locator('#cms-section-preview h1').textContent(),'Aprende hoy. Transforma tu mañana.');assert.equal(await ap.locator('#cms-section-preview .hero').evaluate(el=>el.style.getPropertyValue('--section-background')),'#eef4f0');await ap.locator('[data-cms-image]').setInputFiles(path.resolve('public/uploads/certificates/demo-front.png'));await ap.waitForFunction(()=>document.querySelector('[name="settings.imageUrl"]').value.startsWith('/uploads/'));await ap.locator('[name="settings.imageUrl"]').fill('');await ap.locator('#cms-save').click();await ap.getByText('Borrador guardado.',{exact:true}).waitFor();results.flows.push('CMS: texto y colores en vista en vivo, subida de imagen y borrador');
  // Put the hero back before featured courses, then add and publish the footer block.
  await ap.locator('[data-move="1"][data-direction="-1"]').click();await ap.locator('#cms-add').click();await ap.locator('#new-section-type').selectOption('footer');await ap.locator('#confirm-section').click();await ap.locator('[name="settings.title"]').fill('Tu próximo paso empieza aquí.');await Promise.all([ap.waitForResponse(r=>r.url().endsWith('/api/admin/cms/home/publish')&&r.status()===200),ap.locator('#cms-publish').click()]);await ap.waitForLoadState('networkidle');await gp.goto(base+'/');await gp.locator('.home-footer').waitFor();assert.equal(await gp.locator('.home-footer a[href="/privacidad"]').count(),1);assert.equal(await gp.locator('.home-footer a[href="/terminos"]').count(),1);assert.equal(await gp.locator('#site-footer').isVisible(),false);assert.equal((await request(guest,'/api/site')).home.sections.at(-1).section_type,'footer');await gp.goto(base+'/catalogo');await gp.locator('.catalog-filter-details summary').waitFor();assert.equal(await gp.locator('.catalog-filter-details').evaluate(el=>el.open),false);await gp.locator('.catalog-filter-details summary').click();await gp.locator('#catalog-filters').waitFor();assert.equal(await gp.locator('#site-footer').isVisible(),true);results.flows.push('CMS: publicación real con pie de página sin duplicar footer; otras rutas conservan su pie');

  const routes=[{page:gp,paths:['/','/catalogo','/curso/qa-course','/login','/registro','/recuperar','/reset-password?token=demo','/privacidad','/terminos']},{page:sp,paths:['/dashboard','/pago?course=ia','/aula/qa-course',`/certificado/${cert.certificate.code}`]},{page:ap,paths:['/admin/resumen','/admin/usuarios','/admin/pagos','/admin/cursos','/admin/cms','/admin/sedes','/admin/cupones','/admin/certificados','/admin/configuracion','/admin/diseno','/admin/auditoria','/?preview=1']}];
  for(const {page}of routes){page.on('pageerror',e=>results.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')results.errors.push(m.text())});}
  for(const width of results.widths){
   for(const {page,paths}of routes){await page.setViewportSize({width,height:900});for(const route of paths){await page.goto(base+route);await page.locator('#main').waitFor();await page.waitForFunction(()=>document.querySelector('#main')?.innerText.trim().length>10&&!document.querySelector('#main .loading-state'));await page.evaluate(()=>document.fonts.ready);const geometry=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,error:document.body.innerText.includes('No se pudo cargar esta vista')}));assert.ok(!geometry.error,route);if(geometry.scrollWidth>width+1){const elements=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>{const b=el.getBoundingClientRect();return b.width&&b.right>innerWidth+1&&!el.closest('.table-wrap,.carousel__track,.admin-sidebar nav,.nav');}).map(el=>({tag:el.tagName,class:el.className,text:el.textContent.slice(0,100),right:el.getBoundingClientRect().right})));results.overflows.push({width,route,...geometry,elements});}const filename=width+'-'+(route.replace(/[^a-z0-9]/gi,'-').slice(0,80)||'home')+'.png';await page.screenshot({path:path.join(out,filename),fullPage:true});results.pages.push({width,route,...geometry,screenshot:filename});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}
   }
   await gp.goto(base+'/');if(width<=1100){await gp.locator('#menu-btn').waitFor();await gp.locator('#menu-btn').click();assert.equal(await gp.locator('#menu-btn').getAttribute('aria-expanded'),'true');await gp.keyboard.press('a');await gp.keyboard.press('Escape');assert.equal(await gp.locator('#menu-btn').getAttribute('aria-expanded'),'false');}
  }
  results.flows.push('Menú móvil: abre, tecla normal seguida de Escape cierra');
  const uiContext=await browser.newContext(),uiPage=await uiContext.newPage();await uiPage.goto(base+'/registro');await uiPage.locator('#name').fill('Alumno de formulario');await uiPage.locator('#email').fill('form@qa.local');await uiPage.locator('#password').fill('QA-form-password-2026!');await uiPage.getByRole('button',{name:'Crear cuenta',exact:true}).click();await uiPage.waitForURL('**/dashboard');await uiPage.locator('#logout-btn').click();await uiPage.waitForURL(base+'/');await uiPage.goto(base+'/login?next=%2Fcurso%2Fqa-course');await uiPage.locator('#email').fill('form@qa.local');await uiPage.locator('#password').fill('QA-form-password-2026!');await uiPage.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await uiPage.waitForURL('**/curso/qa-course');results.flows.push('Registro, logout y login por formularios reales; destino next interno respetado');await uiContext.close();
  const logout=await request(student,'/api/auth/logout','POST',{},stu.csrfToken);assert.equal(logout.ok,true);assert.equal((await request(student,'/api/auth/me')).user,null);results.flows.push('Logout destruye la sesión');
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));assert.deepEqual(results.errors,[]);assert.deepEqual(results.overflows,[]);console.log(JSON.stringify({pages:results.pages.length,widths:results.widths,flows:results.flows,errors:results.errors},null,2));
 }finally{await browser.close();await app.locals.videoService.close();await new Promise(resolve=>server.close(resolve));closeDatabase();fs.rmSync(temporary,{recursive:true,force:true});}
}
run().catch(error=>{console.error(error.stack);process.exitCode=1;});
